# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1b202ed0809ae84680f0a6daefd01c619bfa6cfbd4475b5d7f9fd599185064d907634726436249678b7c54b3ab51a935b3a8158cf3c4aa265b0c170e102a1eb
  google_api_key: "AIzaSyDT0e-2ul1a83yS1dm1VRp-qcMLCDmpPhU"

test:
  secret_key_base: dfbfe44e621b347a04590e4886a831d81939b9bcf6e5400a28153601d53dc2a9be9b82aa7c69cd9c2463adfaaca3054e769c6e3702412a0b8118b972af0ab3a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_api_key: "AIzaSyDT0e-2ul1a83yS1dm1VRp-qcMLCDmpPhU"
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
